channels:
  - conda-forge
  - ilastik-forge
  - nodefaults

dependencies:
  - python 3.9.*
  - pip
  - ilastik
  - typing_extensions
  - pytest
  - sphericaltexture
  # TODO: add any additional dependencies here
